apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app-deployment
  labels:
    app: counter-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
        - name: counter-app
          image: interview1080/counter:6
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: "/app/data"
              name: counter-app-data
      volumes:
        - name: counter-app-data
          persistentVolumeClaim:
            claimName: counter-app-pvc
